apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config-file
data:
  mosquitto.conf: |
    log_dest stdout
    log_type all
    log_timestamp true
    listener 9001
    
---
apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-secret-file
type: Opaque
data:
  secret.file: |
    c29tZXN1cGVyc2VjcmV0IGZpbGUgY29udGVudHMgbm9ib2R5IHNob3VsZCBzZWU=
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  labels:
    app: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:1.6.2
          ports:
            - containerPort: 1883
          volumeMounts:
            - name: mosquitto-conf
              mountPath: /mosquitto/config
            - name: mosquitto-secret
              mountPath: /mosquitto/secret  
              readOnly: true
      volumes:
        - name: mosquitto-conf
          configMap:
            name: mosquitto-config-file
        - name: mosquitto-secret
          secret:
            secretName: mosquitto-secret-file    

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  labels:
    app: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:1.6.2
          ports:
            - containerPort: 1883

#Explanation:

#This part defines a Deployment named mosquitto that will create and manage a replica of the Mosquitto application (MQTT broker).
#The Deployment ensures that there is always one replica (replicas: 1) of the Mosquitto container running.
#The Deployment uses a selector with the app: mosquitto label to identify the pods that are part of this deployment.
#The pod template under the spec section of the Deployment defines the configuration for the pods that will be created.
#The container within the pod is named mosquitto and uses the image eclipse-mosquitto:1.6.2.
#The container exposes port 1883, which is likely the port used for MQTT communication.
#The volumeMounts section mounts two volumes into the container: mosquitto-conf and mosquitto-secret. These volumes are used to provide configuration files and secrets to the container.
#The volumes section defines the actual volumes used in the pod. Two volumes are defined: mosquitto-conf and mosquitto-secret, and they are associated with the corresponding ConfigMap and Secret created earlier.
#In summary, the YAML file defines a Kubernetes Deployment that runs a single replica of the Mosquitto MQTT broker container. The Deployment uses a ConfigMap to provide the mosquitto.conf configuration file to the container and a Secret to provide some sensitive data in the secret.file.
