apiVersion: v1
kind: Namespace
metadata:
  name: ramki
---
apiVersion: v1
kind: LimitRange
metadata:
  name: ramki-resource-limits
  namespace: ramki
spec:
  limits:
  - default:
      cpu: 500m     # 500 milliCPU (0.5 CPU)
      memory: 512Mi # 512 Mebibytes (MiB)
    defaultRequest:
      cpu: 100m     # 100 milliCPU (0.1 CPU)
      memory: 256Mi # 256 Mebibytes (MiB)
    type: Container
